/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
enum _1_shuffle_buffer_$op ;
union _1_shuffle_buffer_$node ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
enum _1_shuffle_buffer_$op {
    _1_shuffle_buffer__formal$result_STA_0$value_LIT_0 = 7,
    _1_shuffle_buffer__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 168,
    _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 58,
    _1_shuffle_buffer__store_unsigned_char$left_STA_0$right_STA_1 = 163,
    _1_shuffle_buffer__goto$label_LAB_0 = 91,
    _1_shuffle_buffer__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 250,
    _1_shuffle_buffer__Div_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 24,
    _1_shuffle_buffer__local$result_STA_0$value_LIT_0 = 1,
    _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0 = 190,
    _1_shuffle_buffer__store_int$right_STA_0$left_STA_1 = 64,
    _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 132,
    _1_shuffle_buffer__load_int$left_STA_0$result_STA_0 = 103,
    _1_shuffle_buffer__branchIfTrue$expr_STA_0$label_LAB_0 = 35,
    _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0 = 154,
    _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0 = 123,
    _1_shuffle_buffer__load_unsigned_char$left_STA_0$result_STA_0 = 136,
    _1_shuffle_buffer__returnVoid$ = 90,
    _1_shuffle_buffer__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 182,
    _1_shuffle_buffer__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 100,
    _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0 = 3
} ;
unsigned char _1_shuffle_buffer_$array[1][254]  = { {        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__store_int$right_STA_0$left_STA_1,        _1_shuffle_buffer__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__goto$label_LAB_0, 
            (unsigned char)208,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_shuffle_buffer__store_int$right_STA_0$left_STA_1,        _1_shuffle_buffer__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__Div_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__goto$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__goto$label_LAB_0, 
            (unsigned char)144,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0,        _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_shuffle_buffer__load_unsigned_char$left_STA_0$result_STA_0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__store_unsigned_char$left_STA_0$right_STA_1,        _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0,        _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__load_unsigned_char$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0,        _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_shuffle_buffer__store_unsigned_char$left_STA_0$right_STA_1,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_unsigned_char$left_STA_0$result_STA_0,        _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_shuffle_buffer__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0,        _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_shuffle_buffer__store_unsigned_char$left_STA_0$right_STA_1, 
            _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_shuffle_buffer__load_int$left_STA_0$result_STA_0,        _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_shuffle_buffer__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_shuffle_buffer__store_int$right_STA_0$left_STA_1,        _1_shuffle_buffer__goto$label_LAB_0,        (unsigned char)33, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_shuffle_buffer__goto$label_LAB_0, 
            (unsigned char)28,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_shuffle_buffer__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_shuffle_buffer__returnVoid$}};
extern int pthread_join(void *thread ,
                        void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   *format  , ...) ;
extern int pthread_cond_signal(int *cond ) ;
extern int scanf(char const   *format  , ...) ;
extern int raise(int sig ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
void shuffle_buffer(unsigned char *buffer , int n ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void exit(int status ) ;
void main(void) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
union _1_shuffle_buffer_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
char const   *_1_shuffle_buffer_$strings  =    "";
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
void shuffle_buffer(unsigned char *buffer , int n ) 
{ 
  char _1_shuffle_buffer_$locals[21] ;
  union _1_shuffle_buffer_$node _1_shuffle_buffer_$stack[1][32] ;
  union _1_shuffle_buffer_$node *_1_shuffle_buffer_$sp[1] ;
  unsigned char *_1_shuffle_buffer_$pc[1] ;

  {
  _1_shuffle_buffer_$sp[0] = _1_shuffle_buffer_$stack[0];
  _1_shuffle_buffer_$pc[0] = _1_shuffle_buffer_$array[0];
  while (1) {
    switch (*(_1_shuffle_buffer_$pc[0])) {
    case _1_shuffle_buffer__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_int = (_1_shuffle_buffer_$sp[0] + 0)->_int - (_1_shuffle_buffer_$sp[0] + -1)->_int;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__load_int$left_STA_0$result_STA_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 0)->_int = *((int *)(_1_shuffle_buffer_$sp[0] + 0)->_void_star);
    break;
    case _1_shuffle_buffer__load_unsigned_char$left_STA_0$result_STA_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 0)->_unsigned_char = *((unsigned char *)(_1_shuffle_buffer_$sp[0] + 0)->_void_star);
    break;
    case _1_shuffle_buffer__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    if ((_1_shuffle_buffer_$sp[0] + 0)->_int) {
      _1_shuffle_buffer_$pc[0] += *((int *)_1_shuffle_buffer_$pc[0]);
    } else {
      _1_shuffle_buffer_$pc[0] += 4;
    }
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__load_void_star$left_STA_0$result_STA_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 0)->_void_star = *((void **)(_1_shuffle_buffer_$sp[0] + 0)->_void_star);
    break;
    case _1_shuffle_buffer__store_unsigned_char$left_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    *((unsigned char *)(_1_shuffle_buffer_$sp[0] + 0)->_void_star) = (_1_shuffle_buffer_$sp[0] + -1)->_unsigned_char;
    _1_shuffle_buffer_$sp[0] += -2;
    break;
    case _1_shuffle_buffer__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_void_star = (_1_shuffle_buffer_$sp[0] + 0)->_void_star + (_1_shuffle_buffer_$sp[0] + -1)->_unsigned_long;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__returnVoid$: 
    (_1_shuffle_buffer_$pc[0]) ++;
    return;
    break;
    case _1_shuffle_buffer__formal$result_STA_0$value_LIT_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    switch (*((int *)_1_shuffle_buffer_$pc[0])) {
    case 1: 
    (_1_shuffle_buffer_$sp[0] + 1)->_void_star = (void *)(& n);
    break;
    case 0: 
    (_1_shuffle_buffer_$sp[0] + 1)->_void_star = (void *)(& buffer);
    break;
    }
    (_1_shuffle_buffer_$sp[0]) ++;
    _1_shuffle_buffer_$pc[0] += 4;
    break;
    case _1_shuffle_buffer__local$result_STA_0$value_LIT_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 1)->_void_star = (void *)(_1_shuffle_buffer_$locals + *((int *)_1_shuffle_buffer_$pc[0]));
    (_1_shuffle_buffer_$sp[0]) ++;
    _1_shuffle_buffer_$pc[0] += 4;
    break;
    case _1_shuffle_buffer__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_int = (_1_shuffle_buffer_$sp[0] + 0)->_int >= (_1_shuffle_buffer_$sp[0] + -1)->_int;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_shuffle_buffer_$pc[0]);
    (_1_shuffle_buffer_$sp[0]) ++;
    _1_shuffle_buffer_$pc[0] += 8;
    break;
    case _1_shuffle_buffer__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_shuffle_buffer_$sp[0] + 0)->_int;
    break;
    case _1_shuffle_buffer__store_int$right_STA_0$left_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    *((int *)(_1_shuffle_buffer_$sp[0] + -1)->_void_star) = (_1_shuffle_buffer_$sp[0] + 0)->_int;
    _1_shuffle_buffer_$sp[0] += -2;
    break;
    case _1_shuffle_buffer__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_int = (_1_shuffle_buffer_$sp[0] + -1)->_int + (_1_shuffle_buffer_$sp[0] + 0)->_int;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__goto$label_LAB_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    _1_shuffle_buffer_$pc[0] += *((int *)_1_shuffle_buffer_$pc[0]);
    break;
    case _1_shuffle_buffer__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_int = (_1_shuffle_buffer_$sp[0] + 0)->_int < (_1_shuffle_buffer_$sp[0] + -1)->_int;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__constant_int$result_STA_0$value_LIT_0: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + 1)->_int = *((int *)_1_shuffle_buffer_$pc[0]);
    (_1_shuffle_buffer_$sp[0]) ++;
    _1_shuffle_buffer_$pc[0] += 4;
    break;
    case _1_shuffle_buffer__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_unsigned_long = (_1_shuffle_buffer_$sp[0] + 0)->_unsigned_long * (_1_shuffle_buffer_$sp[0] + -1)->_unsigned_long;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    case _1_shuffle_buffer__Div_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_shuffle_buffer_$pc[0]) ++;
    (_1_shuffle_buffer_$sp[0] + -1)->_int = (_1_shuffle_buffer_$sp[0] + -1)->_int / (_1_shuffle_buffer_$sp[0] + 0)->_int;
    (_1_shuffle_buffer_$sp[0]) --;
    break;
    }
  }
}
}
